### ISSUE TITLE
Error while installin package in NextJs 15.0.1

### ISSUE THREAD

**Issue by rushidshinde** [avitorio/outstatic#257]
### Provide environment information

Using Next js 15.0.1 

Package.json
```
{
  "name": "outstatic-blog-js",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "19.0.0-rc-69d4b800-20241021",
    "react-dom": "19.0.0-rc-69d4b800-20241021",
    "next": "15.0.1"
  },
  "devDependencies": {
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "eslint": "^8",
    "eslint-config-next": "15.0.1"
  }
}
```

### Describe the Bug

Console window: 
```
PS C:\Rushi\Home\learn\nextjs\outstatic-blog-js> npm i outstatic
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: outstatic-blog-js@0.1.0
npm error Found: next@15.0.1
npm error node_modules/next
npm error   next@"15.0.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer next@"^13 || ^14" from outstatic@1.4.9
npm error node_modules/outstatic
npm error   outstatic@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\rushi\AppData\Local\npm-cache\_logs\2024-10-25T03_28_21_757Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\rushi\AppData\Local\npm-cache\_logs\2024-10-25T03_28_21_757Z-debug-0.log
PS C:\Rushi\Home\learn\nextjs\outstatic-blog-js>
```

Log file: 

```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.8.3
2 info using node@v20.12.2
3 silly config load:file:C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\npmrc
4 silly config load:file:C:\Rushi\Home\learn\nextjs\outstatic-blog-js\.npmrc
5 silly config load:file:C:\Users\rushi\.npmrc
6 silly config load:file:C:\Users\rushi\AppData\Roaming\npm\etc\npmrc
7 verbose title npm i outstatic
8 verbose argv "i" "outstatic"
9 verbose logfile logs-max:10 dir:C:\Users\rushi\AppData\Local\npm-cache\_logs\2024-10-25T03_28_21_757Z-
10 verbose logfile C:\Users\rushi\AppData\Local\npm-cache\_logs\2024-10-25T03_28_21_757Z-debug-0.log
11 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
12 silly logfile start cleaning logs, removing 2 files
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest outstatic@*
16 silly packumentCache full:https://registry.npmjs.org/outstatic cache-miss
17 http fetch GET 200 https://registry.npmjs.org/outstatic 1330ms (cache revalidated)
18 silly packumentCache full:https://registry.npmjs.org/outstatic set size:335817 disposed:false
19 silly fetch manifest next@15.0.1
20 silly packumentCache full:https://registry.npmjs.org/next cache-miss
21 http fetch GET 200 https://registry.npmjs.org/next 35ms (cache hit)
22 silly packumentCache full:https://registry.npmjs.org/next set size:21500712 disposed:false
23 silly fetch manifest next@^13 || ^14
24 silly packumentCache full:https://registry.npmjs.org/next cache-miss
25 http fetch GET 200 https://registry.npmjs.org/next 37ms (cache hit)
26 silly packumentCache full:https://registry.npmjs.org/next set size:21500712 disposed:false
27 silly fetch manifest @opentelemetry/api@^1.1.0
28 silly packumentCache full:https://registry.npmjs.org/@opentelemetry%2fapi cache-miss
29 http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fapi 11ms (cache hit)
30 silly packumentCache full:https://registry.npmjs.org/@opentelemetry%2fapi set size:455622 disposed:false
31 silly fetch manifest @playwright/test@^1.41.2
32 silly packumentCache full:https://registry.npmjs.org/@playwright%2ftest cache-miss
33 http fetch GET 200 https://registry.npmjs.org/@playwright%2ftest 15ms (cache hit)
34 silly packumentCache full:https://registry.npmjs.org/@playwright%2ftest set size:7139497 disposed:false
35 silly fetch manifest babel-plugin-react-compiler@*
36 silly packumentCache full:https://registry.npmjs.org/babel-plugin-react-compiler cache-miss
37 http fetch GET 200 https://registry.npmjs.org/babel-plugin-react-compiler 6ms (cache hit)
38 silly packumentCache full:https://registry.npmjs.org/babel-plugin-react-compiler set size:209475 disposed:false
39 silly fetch manifest react@19.0.0-rc-69d4b800-20241021
40 silly packumentCache full:https://registry.npmjs.org/react cache-miss
41 http fetch GET 200 https://registry.npmjs.org/react 12ms (cache hit)
42 silly packumentCache full:https://registry.npmjs.org/react set size:5091805 disposed:false
43 silly fetch manifest react-dom@19.0.0-rc-69d4b800-20241021
44 silly packumentCache full:https://registry.npmjs.org/react-dom cache-miss
45 http fetch GET 200 https://registry.npmjs.org/react-dom 16ms (cache hit)
46 silly packumentCache full:https://registry.npmjs.org/react-dom set size:6205003 disposed:false
47 silly fetch manifest sass@^1.3.0
48 silly packumentCache full:https://registry.npmjs.org/sass cache-miss
49 http fetch GET 200 https://registry.npmjs.org/sass 8ms (cache hit)
50 silly packumentCache full:https://registry.npmjs.org/sass set size:640300 disposed:false
51 verbose stack Error: unable to resolve dependency tree
51 verbose stack     at #failPeerConflict (C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1360:25)
51 verbose stack     at #loadPeerSet (C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1326:33)
51 verbose stack     at async #buildDepStep (C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:901:11)
51 verbose stack     at async Arborist.buildIdealTree (C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:181:7)
51 verbose stack     at async Promise.all (index 1)
51 verbose stack     at async Arborist.reify (C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:131:5)
51 verbose stack     at async Install.exec (C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:150:5)
51 verbose stack     at async Npm.exec (C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\lib\npm.js:207:9)
51 verbose stack     at async module.exports (C:\Users\rushi\AppData\Roaming\npm\node_modules\npm\lib\cli\entry.js:74:5)
52 error code ERESOLVE
53 error ERESOLVE unable to resolve dependency tree
54 error
55 error While resolving: outstatic-blog-js@0.1.0
55 error Found: next@15.0.1[2m[22m
55 error [2mnode_modules/next[22m
55 error   next@"15.0.1" from the root project
55 error
55 error Could not resolve dependency:
55 error [95mpeer[39m next@"^13 || ^14" from outstatic@1.4.9[2m[22m
55 error [2mnode_modules/outstatic[22m
55 error   outstatic@"*" from the root project
55 error
55 error Fix the upstream dependency conflict, or retry
55 error this command with --force or --legacy-peer-deps
55 error to accept an incorrect (and potentially broken) dependency resolution.
56 error
56 error
56 error For a full report see:
56 error C:\Users\rushi\AppData\Local\npm-cache\_logs\2024-10-25T03_28_21_757Z-eresolve-report.txt
57 silly unfinished npm timer reify 1729826902057
58 silly unfinished npm timer reify:loadTrees 1729826902060
59 silly unfinished npm timer idealTree:buildDeps 1729826902147
60 silly unfinished npm timer idealTree:#root 1729826902147
61 verbose cwd C:\Rushi\Home\learn\nextjs\outstatic-blog-js
62 verbose os Windows_NT 10.0.22631
63 verbose node v20.12.2
64 verbose npm  v10.8.3
65 verbose exit 1
66 verbose code 1
67 error A complete log of this run can be found in: C:\Users\rushi\AppData\Local\npm-cache\_logs\2024-10-25T03_28_21_757Z-debug-0.log
```

### Expected Behavior

Expecting to install outstatic successfully 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

#

### To Reproduce

first create next app 
```npx create-next-app@latest```

install outstatic
```npm i outstatic```

**Comment by avitorio** [comment]
Hey @rushidshinde ,
We are currently not supporting next 15 yet. 
A new version with 15 support should come up in the next few days. Cheers.
